### ISSUE TITLE
Name must not be blank error when attempting to save form

### ISSUE THREAD

**Issue by yanokwa** [opendatakit/opendatakit#1172]
Reported by Hayden Boyd.

We are using ODK Collect to record Marion Medical Mission well installations in Malawi, Tanzania, and Zambia.  We are experiencing a (thankfully) rare error when attempting to save an installation form. The form is currently set up to display an instance name at the end page.  Several times (4 times in 1,000 plus installations, each time on a different one of the 14 tablets deployed), the name that should appear on the "Save Form and Exit" page is blank, and the "Name must not be blank" error message displays when one attempts to save the finalized form.  The instance name is supposed to be displayed automatically, and there is no text box or other way to specify a name by hand on the last page. The remedy in the field is to discard the filled form and start over - a major annoyance since the villagers must be reassembled for the well picture.  My attempted fix has been to uncheck "Name this form" in Administrative settings as I gain access to the tablets, but since the problem is so rare, it is hard to determine whether this is the proper solution.  I would appreciate advice on what more, if anything, should be done to prevent this problem.

For background, here is some information that might be relevant:
ODK Collect 1.4.7 (1053), Android version 5.1.1, Google Nexus 7 tablets (2013 model)
Instance name is of the form Zone_village_date, specified in the XLSForm  settings instance_name as:
concat(${Zone}, ${OtherZone}, "_", ${Village}, "_",  ${InstallDate}) where Zone is a select_one variable, OtherZone is text which is relevant when Zone='Other' is selected, Village is text (all required), and InstallDate is type 'start' and entered automatically.

**Comment by mitchellsundt** [comment]
We would need a zip of the /sdcard/opendatakit directory on the tablet
before we could attempt to solve this.

This wouldn't fix the issue, but I wonder if...

When this happens:

 if you swipe backward to the previous question,
 then hit the back button (so that it pops up the Save as Incomplete /
Ignore changes pop-up),
 choose Save as Incomplete
 does it save and exit the form?

And if that works, then what happens if:

   you edit the saved form
   jump to the last question,
   swipe forward and finalize?






On Tue, Oct 6, 2015 at 3:48 PM, Yaw Anokwa <notifications@github.com> wrote:

> Reported by Hayden Boyd.
>
> We are using ODK Collect to record Marion Medical Mission well
> installations in Malawi, Tanzania, and Zambia. We are experiencing a
> (thankfully) rare error when attempting to save an installation form. The
> form is currently set up to display an instance name at the end page.
> Several times (4 times in 1,000 plus installations, each time on a
> different one of the 14 tablets deployed), the name that should appear on
> the "Save Form and Exit" page is blank, and the "Name must not be blank"
> error message displays when one attempts to save the finalized form. The
> instance name is supposed to be displayed automatically, and there is no
> text box or other way to specify a name by hand on the last page. The
> remedy in the field is to discard the filled form and start over - a major
> annoyance since the villagers must be reassembled for the well picture. My
> attempted fix has been to uncheck "Name this form" in Administrative
> settings as I gain access to the tablets, but since the pr oblem is so
> rare, it is hard to determine whether this is the proper solution. I would
> appreciate advice on what more, if anything, should be done to prevent this
> problem.
>
> For background, here is some information that might be relevant:
> ODK Collect 1.4.7 (1053), Android version 5.1.1, Google Nexus 7 tablets
> (2013 model)
> Instance name is of the form Zone_village_date, specified in the XLSForm
> settings instance_name as:
> concat(${Zone}, ${OtherZone}, "*", ${Village}, "*", ${InstallDate}) where
> Zone is a select_one variable, OtherZone is text which is relevant when
> Zone='Other' is selected, Village is text (all required), and InstallDate
> is type 'start' and entered automatically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opendatakit/opendatakit/issues/1172>.
>



-- 
Mitch Sundt
Software Engineer
University of Washington
mitchellsundt@gmail.com

**Comment by haydenboyd** [comment]
Mitch,

I have uploaded a zip file of the \sdcard\odk directory to Dropbox, along with the XLSForm source file for the Install2015 form that experienced the problem (I don't see an "opendatakit" directory there). The zip file is from my own tablet (one of the 4 tablets that experienced the problem), prepared as part of the daily backup routine. I will "share" the Dropbox folder if you would post directions on how we should exchange our respective email addresses.

Because we need a photo with each well record, none of the cell phone networks in our three African countries have sufficient bandwidth to submit the completed forms. Instead, we use Wi-Fi only tablets and submit to a local server via Wi-Fi after a few weeks when the installation teams come back in from the field. Incomplete forms could require revisiting often-remote well sites to complete the record, so ODK Collect is configured to allow only finalized and validated forms to be saved.  I'm hopeful that (1) unchecking "Name this form" in admin settings will solve the problem, but, if not, (2) we will follow Yaw's suggestion to reboot with the problem form open in ODK Collect, or, it that fails, (3) we will again discard the problem form and start over. Fortunately, the problem has occurred rarely. 

Thanks for your help on this problem.

All the best, Hayden

**Comment by mitchellsundt** [comment]
My e-mail is mitchellsundt@gmail.com
