### ISSUE TITLE
odk-collect do not have support of relative paths (or so it seems)

### ISSUE THREAD

**Issue by agap** [opendatakit/opendatakit#1225]
We have a cascading select in the repeating group and the cascading select itself has a choice filter applied to it. So the list of values of second `select-multiple` item is filtered accordingly to the item selected in the first `select-multiple` item and the list of values of the third `select-multiple` item is filtered acordingly to the items selected in first and the second `select-multiple` sections.
We were using this syntax to access the previous item before: `category_part=${category_part}` but turns out it fails on a second run as descibed in [this thread](https://groups.google.com/forum/#!topic/opendatakit-developers/V4yWbpEs-EA). It is also said in this thread that we can overcome the issue by using `current()` with relative paths. I [found ](https://github.com/opendatakit/opendatakit/issues/887)that the javarosa supports `current()` starting from the 1.4.3, but it seems that the current version of odk-collect does not support `current()` with relative paths - whenever I open the second `multiple-select` item in the app, I see the empty screen w/o any values. 
Am I doing something wrong or the odk-collect does not support relative paths yet?

I'm writing my filters like so:

part_category=current()/../part_category
part_category=current()/../../part_category and part_type=current()/../part_type

**Comment by mitchellsundt** [comment]
Please use the opendatakit@ lists for questions of this type.  Also provide a slimmed-down form demonstrating the issue -- it will be more likely to get attention and assistance.

The code has not changed and current()/.. is still working.

I assume you are not trying to display the dependent select-multiple on the same field-list screen as the first question -- that does not work. You need to place the dependent questions on subsequent pages so that they can use the data values collected from the answers to the earlier questions.
