### ISSUE TITLE
Can we create events or triggers on the controls that we use in ODK

### ISSUE THREAD

**Issue by ayushi230490** [opendatakit/opendatakit#1237]
Hi all, I Wanted to know that can we call events or something of that sort in ODK.
Eg: I have a dropdown with some values and I want that if it chooses 1 then to do something x and if 2 then something y like randomly select one number and display??

In Short, can we play on ODK like in Web Development in C# or MVC??

**Comment by mitchellsundt** [comment]
Is this an ODK 2.0 question or a question about ODK Collect ?

**Comment by ayushi230490** [comment]
It's a question on form designing in ODK, using excel.

**Comment by mitchellsundt** [comment]
There are two different set of tools:

 ODK Collect, XLSForm and ODK Aggregate, 

and 

 ODK Survey, XLSXConverter, and ODK 2.0 Tables Extensions for ODK Aggregate.

I assume your question is about forms designed for ODK Collect. For those, you would use the relevant column to define when subsequent questions should be asked. If the formula in the relevant column evaluates to false, the prompt or entire group, if on a begin group row, will be skipped.

**Comment by ayushi230490** [comment]
Ya, I am aware of that, but my situation is that I have few options suppose A,B,C,D,E and I want when the user reaches this question any one option amongst them is chosen randomly. How to implement this, please assist.

**Comment by mitchellsundt** [comment]
OK. So you do not want the user to make a choice, you want the form to make a choice. In that case, you would use a calculate field to compute which of the choices you want to make relevant, and have relevant conditions on all of the questions so that they are only asked if that calculate field indicates that they should be asked. In this case, you would use a calculate field:
once(int(random()*N))

this computes a value that ranges from 0, 1, 2, ... N.

Because of limitations in XLSForm, this field is a string value field.

So you would do relevant conditions like   ${abovefield} = "2"

If you need to dynamically compute this 0, 1, 2... N based upon other information (e.g., N can change), then you should have two calculate fields, one to save the random number ( once(random()) ), and the other that is dynamically computed (without the once() wrapping it).

**Comment by echiteri** [comment]
Hi Mitch,

I have almost the same problem. Except  in my case, I have a group of questions with only the parent question appearing on the screen. If the response to the question is is 'Yes', the other questions on this group, in the same screen, needs to appear, without swiping. This is on ODK collect. I need to program the trigger on the ODK build to activate the other questions on selection.

Regards,

**Comment by mitchellsundt** [comment]
echiteri: that is not possible in ODK Collect. cross-dependence among questions is not possible within the same page. They need to be split across pages.
