### ISSUE TITLE
Please release new ODK Collect 1.4x APK on Google Play

### ISSUE THREAD

**Issue by lindsay-stevens** [opendatakit/opendatakit#1247]
The current release of ODK Collect on the Google Play Store is v1.4.10_rev_1061, as is on GitHub. 

Shortly after this release, a bug was fixed, whereby the relatively recently added Markdown processing code would throw a NPE / crash ODK Collect if the text it is passed to process is null. This can happen for example when a question label is just an image, with no plain text. The fix is in this commit: https://github.com/opendatakit/collect/commit/8257124805b719b16029d2b625b9fe88bcec6c6b. 

In more recent commits, further enhancements were made to the Markdown code to make it match Enketo, as well as the merging of bunch of new geospatial features, which I think would warrant a release.

If there is anything I can do to assist with preparing the release please let me know. I have the impression though that the APK generation / signing / upload has to be done by a core developer with the appropriate credentials.

**Comment by yanokwa** [comment]
Hi Lindsay! I hear you and we do need your help.

Since Collect is going through a transition, I'd like to do this in phases. First, we move all related issues to the Collect repo, triage those issues, merge all the pending pull requests, then do a release and document that process. Then I'd also like to set up some build servers so we can generate continuous builds of APKs so we are never blocking.

My first ask of you is to respond to the questions I'm sending to the developer list about these very issues. Your feedback and willingness to help is really really appreciated. https://groups.google.com/forum/#!topic/opendatakit-developers/2k8q-2B9nXE

**Comment by lindsay-stevens** [comment]
Hi Yaw,

Thanks for getting back to me. I replied to the thread, but it's currently awaiting moderation, since it's my first post. 

Did you have any particular provider in mind for builds? Travis' Android builds are in beta, and CircleCI does them too. Or would you rather set up something custom e.g. with Jenkins etc.?

On a related note, do you think it would be worth absorbing the javarosa fork currently on Mitchell Sundt's BitBucket (https://bitbucket.org/m.sundt/javarosa) into the OpenDataKit organisation on GitHub? Reasons:
- There are a few ODK repo issues that reference it,
- It's a dependency for ODK tools (Collect, Validate)
- The original https://bitbucket.org/javarosa/javarosa repo hasn't been updated since 2011,
- From what I've seen, the ODK Collect forks that need J2ME have sorted it out for themselves, e.g. dimagi's commcare suite.

**Comment by yanokwa** [comment]
Agreed that the Javarosa repo needs to be moved. I've moved a copy to https://github.com/opendatakit/javarosa. @mitchellsundt will this cause a problem for you?

Let's continue the CI conversation on the mailing list.

**Comment by yanokwa** [comment]
We got it out :)

**Comment by lindsay-stevens** [comment]
Thanks Yaw :)
