### ISSUE TITLE
Document using offline maps

### ISSUE THREAD

**Issue by florianm** [opendatakit/opendatakit#1260]
ODK Collect (1.4.11) lists support for offline base maps in the Google Play store. This would be the ultimate "ESRI Collector killer" feature for us.

As much as I would like to use offline maps, I can't seem to find any documentation on how to set up and use offline maps, neither in the ODK docs nor in the XLS-form [reference](http://xlsform.org/ref-table/).

If anyone could point me in the right direction, I'd be happy to PR a docs section on using offline maps.

**Comment by yanokwa** [comment]
It's on my todo list!

**Comment by florianm** [comment]
Thanks @yanokwa ! No rush :-)

**Comment by lognaturel** [comment]
@florianm You might find some of what I described [here](https://github.com/opendatakit/collect/pull/1045#issuecomment-305356422) useful! 

I've also filed it at opendatakit/docs#3 in the exciting new docs repo where hopefully it will be picked up soon.

**Comment by dig360** [comment]
Hello everybody,
I'm reading for many days differents post about using offline overlay layers for ODK Collect without success. I've tried with geoODK and found a working way to display an mbtiles. With ODK Collect I'm not able to display the choice popup with my overlay, only the none option is available.
I've attempted differents folders like : 
- /"name of sdcard"/odk/layers/myfile.mbtiles;
- /"phone memory"/odk/layers/myfile.mbtiles.

Nothing appear by the choice popup.
Can you help me to understand where I'm doing wrong ?
Thank you and my apologies for my english !
Didier of Geneva

**Comment by chrislrobert** [comment]
Didier, the issue could be this: offline map tiles have to be in subdirectories off of /odk/layers, not in the root layers directory itself. So try, for example, putting your tiles in a subdirectory like this:

/odk/layers/mytiles

We weren't able to get these features through our QC processes in time for our latest release, so we haven't yet completed documentation yet. The most difficult area concerns support for offline tiles: it's vitally important, but also extremely tricky. For example, you need to save tiles for every possible zoom level you might require, and if you don't then the experience for users trying to use maps offline is extremely poor.

Our QC team has begun assembling very rough internal documentation, in advance of us creating something more user-facing. In case it's useful, I'll share what we have so far -- but it says very little about how offline tiles can be used.

[SurveyCTO Geo Very Rough Prelim Documentation.docx](https://github.com/opendatakit/opendatakit/files/1091239/SurveyCTO.Geo.Very.Rough.Prelim.Documentation.docx)

Most of what we say here applies equally to the trunk/ODK implementation, but:

* We call the offline layers directory /SurveyCTO/layers whereas for you/ODK it's /odk/layers
* We hid the mapping-engine options by default and called them "Advanced mapping options" in the UI, but for you/ODK it's just "Mapping engine", I believe.

We'll continue to share fixes and then eventual documentation, but because we couldn't make these features "supportable" in our latest release, the timeline has been pushed back significantly. I'm not sure when we'll finish our work, but we might chip away at it gradually over time.

**Comment by dig360** [comment]
Thank you very much "chrislrobert".
Work's fine with my mbtiles file placed in a folder like you explain to me.
In my case, it's to locate an event in a small part of land like a music festival for reporting and monitoring. I produced a tileset with about 10'000 tiles for a 20Mb file size, I used QGIS to make it. No problem.
I would like ask about one more information for catching the values of positonned point. Is it possible by an calculate field or any other method. I have installed an odkaggregate on my server and I would like to push this in my spatial db (Postgis).
Best Regards
Didier

**Comment by chrislrobert** [comment]
Sorry, Didier, for not responding earlier. Unfortunately, I have nothing
helpful to suggest with respect to calculating anything from geoshape or
geotrace fields. For normal geopoint fields that are in a repeat group,
there is the area() function within the form itself, and then there's a
discussion somewhere about adding support for SurveyCTO's
distance-between() function (appropriately renamed after community
discussion about naming conventions and personal preferences).

**Comment by chrislrobert** [comment]
One of our QC team added their tips on using offline tiles. In case it's helpful, I attach our latest draft here:

[SurveyCTO Geo Very Rough Prelim Documentation v2.docx](https://github.com/opendatakit/opendatakit/files/1102114/SurveyCTO.Geo.Very.Rough.Prelim.Documentation.v2.docx)

**Comment by dig360** [comment]
Very usefull !
many thank's.
I'm using QGIS to produce my mbtiles files successfully.

**Comment by lognaturel** [comment]
Closing in favor of opendatakit/docs#3
