### ISSUE TITLE
Show more menu items as action

### ISSUE THREAD

**Issue by linl33** [opendatakit/opendatakit#1376]
In the menu bar of ODK 2 apps, many items are hidden under the overflow section. If the screen size allows, some should be marked "showAsAction" to be placed in the top-level. 

![screenshot from 2018-02-21 10-09-18](https://user-images.githubusercontent.com/8204095/36497359-fe1f8ef4-16ef-11e8-8366-c685617685b4.png)

**Comment by lakshyagupta21** [comment]
I've tried to see the how it shows menu in different screen orientation

**Portrait mode**
![ezgif com-resize](https://user-images.githubusercontent.com/18495162/36582061-e1ffda10-1895-11e8-881d-633776fddbc3.png)

**Landscape mode**
![ezgif com-resize 1](https://user-images.githubusercontent.com/18495162/36582064-e2538638-1895-11e8-9761-a36a299e910e.png)

We can modify menu item attributes to `android:showAsAction="always"` to forcefully show the icon in the toolbar but only for some high priority menu items (two or three at max) otherwise it will overlap with action bar title.   

@jbeorse How you want me to proceed?

**Comment by jbeorse** [comment]
Hi @lakshyagupta21. My understanding was that if we changed them to `android:showAsAction="ifRoom"` that it would fill whatever available space there was. I got that idea here: https://developer.android.com/guide/topics/resources/menu-resource.html

Are they currently set like that? If Android is forcing us to have only 3 max showing, then that's fine. I'd rather follow Android's convention. I would recommend ensuring all menu options in ODK Services, ODK Survey, and ODK Tables are set to "ifRoom" and have appropriate icons to display, except for the "About" option, which should be set to 'android:showAsAction="never"`.  Please let me know if my understanding here is incorrect.

**Comment by lakshyagupta21** [comment]
Hi @jbeorse thanks for the reply, okay then I'll set the `showAsAction="ifRoom"` for all the items except 'About' it will take care of both the screen orientation as well as screen sizes.

**Comment by lakshyagupta21** [comment]
@jbeorse I've created a PR in services as well as tables. In survey every menu item are already set to "ifRoom"  except "About" which is set to "never".

**Comment by jbeorse** [comment]
@lakshyagupta21 Thanks! These look great. I've gone ahead and merged them. Please do the same for Survey and I'll close this issue.

**Comment by lakshyagupta21** [comment]
Hi @jbeorse, I've checked the menu items in Survey and everything seems perfect, there is nothing that requires any change related to menu. If you find one let me know.

**Comment by jbeorse** [comment]
Hi @lakshyagupta21 you're right; they're defined in MainMenuActivity.java in the onCreateMenuOptions function in Survey, and they are already set appropriately (though it seems to me long term we should be moving this to an xml file too). I'll go ahead and close this. 

Feel free to grab another issue you find interesting. #1372 might be a good one.
