### ISSUE TITLE
Options for Tables table ordering

### ISSUE THREAD

**Issue by linl33** [opendatakit/opendatakit#1377]
Like #1370 but for Tables.

**Comment by himanshusagar** [comment]
@opendatakit-bot claim

**Comment by himanshusagar** [comment]
@jbeorse @wbrunette @linl33 
Hi All,
I'm working on this issue and need some help so as to understand design of code, which i believe governs dev's ideology and it's beautiful use of fragments. 

From my understanding, code places markers on map for all locations(encircled in image) written in list view.
What I understood:
A. mQueries is of size 2 because atmost 2 UI fragments are displayed at a time. mQueries specifies how data is fetched from db.
B.  I see a for loop in function **setMarkers**(line 329 of TableMapInnerFragment.java ) used for populating list of places in MAP+LIST View and setting hues for Markers

My Questions:
1.  What's an ArbitaryQuery? is it just an alias for SimpleQuery with some options specified.
2.  I don't understand how list of places is populated in LIST View (see attached screenshot; I am talking about this view).

**Comment by jbeorse** [comment]
Hi @himanshusagar. Thanks for looking into this issue. These are great questions.

1. An ArbitraryQuery and a SimpleQuery both do essentially the same thing. They will query the database and return results to your app. However, SimpleQuery is more limited in what it can query, but also comes with built in protections like data permission filters. On the other hand, ArbitraryQuery allows you essentially full freedom to write whatever SQL query you want, bypassing protections, and possibly causing harm. So generally we would recommend using SimpleQuery unless absolutely necessary and you understand what you are doing.

2. The list is populated in Javascript. Look at this file: https://github.com/opendatakit/app-designer/blob/master/app/config/tables/geotagger/js/geo_list.js . It is launched with a query and then uses the results of that query to populate the list. This documentation page goes into more detail: http://opendatakit-dev.cs.washington.edu/2_0_tools/release/218/tables

Back to the issue itself. This will not require Javascript changes. It is very similar to this issue: https://github.com/opendatakit/opendatakit/issues/1370
You can can look to this pull request for some ideas: https://github.com/opendatakit/survey/pull/42

**Comment by jbeorse** [comment]
Address with PR https://github.com/opendatakit/tables/pull/66
