### ISSUE TITLE
Zebra MZ220 printer driver crash

### ISSUE THREAD

**Issue by mitchellsundt** [opendatakit/opendatakit#904]
Originally reported on Google Code with ID 903

```
I installed the Zebra printer and drivers as per: http://opendatakit.org/use/sensors/zebra-printer-driver/
Everything seems fine, until I try to print from the data collection screen. After
clicking the print button, I get the pop-up again to enter the 'Authentication PIN',
communication is started with the printer (the blue light is flashing) after a while
I get a pop-up that says: 'Unfortunately, ODK Zebra Printer has stopped.' Reinstalling
the printer driver, or resetting the tablet did not help.

The device that I am using is a Samsung Galaxy Tab GT-P3100 with Android version 4.0.3.
ODK Collect version 1.3. Zebra MZ220 printer.

Attached it the simple form I am testing with.

Any advise to get the printer working is highly appreciated.
Thanks, Robert

```

Reported by `aighd.org` on 2013-09-03 14:32:24

<hr>
- _Attachment: [PrinterTest.xml](https://storage.googleapis.com/google-code-attachments/opendatakit/issue-903/comment-0/PrinterTest.xml)_

**Comment by Tomonori12** [comment]
It has been a while since I posted my comment.  As follow the official instruction (https://opendatakit.org/help/form-design/examples/#printing_widgets), I made the attached xml form (DemoTestPrinter01.xml).  

The created form can be uploaded to ODK Aggregate v1.4.9, and also can be downloaded to the android tablet/phone. 
`<bind nodeset="/Demo/printLabel" readonly="true()" type="string" calculate="concat('<br>','<br>Customer Name:<br>',/Demo/CustomerName)"/>`

But once i tried to open the empty form, the ODK Collet crushes.  Then, i found that if i follow the official instruction and write `'<br>'` in the calculation syntax, it always crushes the ODK Collect.  

If i remove `'<br>'` and put '123' (digits), the ODK Collect stops crushing (see attached DemoTestPrinter02.xml).  
`<bind nodeset="/Demo/printLabel" readonly="true()" type="string" calculate="concat('123','123',/Demo/CustomerName)"/>`

But now it crushes ODK Zebra Printer application.  So, i also removed `/Demo/CustomerName` and put '123' as below (DemoTestPrinter03.xml).  
`<bind nodeset="/Demo/printLabel" readonly="true()" type="string" calculate="concat('123','123','123')"/>`

Then, it seems that tablet and phone seems communicating (i.e. bluetooth indicator of MZ220 printer is flashing).  But nothing happens even if i wait more than 10 min.

I understand that removing `'<br>'` from the XFrom may not guarantee the proper works for MZ220.  That's just to specify the problem.  Now I'm wandering this can be a version dependency error. So, I'm planing to try with previous versions of ODK Collect.  But for the time being, i couldn't find previous versions.

Any suggestions will be welcomed.

My testing environment is: 
  MZ220 (firmware: S3MZ9519, software version: SHSMZ11z52)
  Nexus 2012 with CyanogenMod 13
     installed - ODK Collect 1.4.10 (1061),  and   ODK Sernser  and  ODK Zebra Printer

[DemoTestPrinter.zip](https://github.com/opendatakit/opendatakit/files/540681/DemoTestPrinter.zip)

Best regards,
Tomonori

**Comment by mitchellsundt** [comment]
Does the example form here:
 https://drive.google.com/drive/folders/0ByL2Z0RJHwGaZ2RTN1BWUXhZazg?usp=sharing

work?

This is the test form used to confirm the operation of the printer.

**Comment by Tomonori12** [comment]
Dear Mitchell Sundt,

Thank you very much for your reply.  AWESOME!!!  It works!!!  I cannot still believe that my printer actually works without crashing.  I was almost throwing away my printer. 

I will check XLSform and XForm more to understand how to write a correct syntax. 

Again, thank you very much. 

Sincerely,
Tomonori Hoshi

**Comment by rannyjohns** [comment]
I appreciate the explanation of the different scanning options. When doing research away from home I currently use my printer try [Epson error code 0x97](http://printertechsupportnumbers.com/blog/fix-epson-wf-3620-error-code-0x97/) that is more helpful to solve the printer problems.
